#!/bin/bash

#This script returns the linked libraries of $1 which contain a certain type with name $2
#Example findLibraryContainingType myBinary some_function

if [ $# -lt 2 ]; then
    (>&2 echo "You need to provide two parameters: \$1=binaryname, \$2=typename")
    exit
fi

lddOutpout=$(ldd -r "$1")

while read line; do
    IFS=' ' read -ra PARTS <<< "$line"
    if [[ "$line" == *"=>"* ]]; then
        libPath="${PARTS[2]}"
    else
        libPath="${PARTS[0]}"
    fi
    foundLines=$(nm "$libPath" 2>/dev/null | grep "$2")

    if [ -n "$foundLines" ]; then
        echo
        echo "$libPath"
        echo "$foundLines"
    fi

done <<< "$lddOutpout"
