#!/bin/bash

#This script returns all libraries in $1 which contain a certain type with name
#$2
#Example findLibraryContainingType rootdir some_function

if [ $# -lt 2 ]; then
    (>&2 echo "You need to provide two parameters: \$1=searchdir, \$2=typename")
    exit
fi

function process () {
    foundLines=$(nm "$1" 2>/dev/null | grep "$2")
    if [ -n "$foundLines" ];then
        echo
        echo "$1"
        echo "$foundLines"
    fi
}

find "$1" -name '*.so' | while read lib;do
    process $lib $2
done

unset process
