#!/bin/bash

#apt
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo apt autoremove
sudo apt autoclean

#npm
sudo npm -g update

#Pip
sudo pip2 install --upgrade pip
sudo pip3 install --upgrade pip
