#!/bin/bash

#apt
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo apt autoremove
sudo apt autoclean

#npm
sudo npm -g update

#Pip
sudo pip2 install --upgrade pip
#sudo pip2 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
#pip2 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
sudo pip3 install --upgrade pip
#sudo pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
#pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U

#Snap
sudo snap refresh
